version: '3'

services:
  db:
    build:
      context: ./database
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data    #saved in /var/lib/docker/volumes

  walletdestroyer:
    build: .
    ports:
      - "7000:7000"
    networks:
      - my_network
    depends_on:
      - db


  nginx:
    build:
      context: ./Nginx
    ports:
      - "8000:8000"
    networks:
      - my_network
    restart: "on-failure"

networks:
  my_network:

volumes:
  postgres_data: