# Generated by Django 4.2.4 on 2023-09-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletdestroyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earningmodel',
            options={'ordering': ['time_create'], 'verbose_name': 'Заработок'},
        ),
        migrations.AlterModelOptions(
            name='spendingmodel',
            options={'ordering': ['time_create'], 'verbose_name': 'Траты'},
        ),
        migrations.AlterField(
            model_name='earningmodel',
            name='time_create',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='spendingmodel',
            name='time_create',
            field=models.DateField(),
        ),
    ]
