# Generated by Django 4.2.4 on 2023-09-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        '0001_initial'
    ]

    # TODO: create spending types
    operations = [

    ]
