# Generated by Django 4.2.4 on 2023-09-17 14:27

from django.db import migrations, models


def add_types(apps, schema_editor):
    categories_model = apps.get_model('walletdestroyer', 'SpendingCategoriesModel')
    names = ['Household', 'Subscriptions', 'Shops', 'Restaurants']
    for name in names:
        categories_model.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('walletdestroyer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_types)
    ]
