# Generated by Django 4.2.4 on 2023-09-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletdestroyer', '0003_rename_spending_type_spendingmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendingtypesmodel',
            name='type_name',
            field=models.CharField(max_length=30),
        ),
    ]
