# Generated by Django 4.2.4 on 2023-09-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletdestroyer', '0004_alter_spendingtypesmodel_type_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpendingTypesModel',
            new_name='SpendingCategoriesModel',
        ),
    ]
