# Generated by Django 4.2.4 on 2023-09-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletdestroyer', '0005_rename_spendingtypesmodel_spendingcategoriesmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spendingcategoriesmodel',
            old_name='type_name',
            new_name='name',
        ),
    ]
