# Generated by Django 4.2.4 on 2023-09-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walletdestroyer', '0006_rename_type_name_spendingcategoriesmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earningmodel',
            options={'ordering': ['-time_create'], 'verbose_name': 'Заработок'},
        ),
        migrations.AlterModelOptions(
            name='spendingmodel',
            options={'ordering': ['-time_create'], 'verbose_name': 'Траты'},
        ),
    ]
