# Generated by Django 4.2.4 on 2023-09-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walletdestroyer', '0007_alter_earningmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningmodel',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spendingmodel',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
